{{- if and (not .Values.auth.telegram.existingSecret) .Values.auth.telegram.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" .Values.auth.telegram.existingSecret "defaultNameSuffix" "telegram" "context" $) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.telegram.token }}
  telegram-token: {{ .Values.auth.telegram.token | b64enc | quote }}
  {{- end }}
{{- end }}
